# Overwrites your current .emacs, assuming it's at ~/.emacs

import datetime
import os

EMACS = os.path.expanduser("~/.emacs")
EMACS_BAK = EMACS + ".bak"
REPO_PATH = os.path.abspath(".")
REPO_EMACS = os.path.abspath("./.emacs")

def backupEmacs():
    # src: https://stackoverflow.com/questions/25851314/making-a-backup-file-appending-date-time-moving-file-if-the-file-exists-pyt
    if os.path.isfile(EMACS):
        modified_time = os.path.getmtime(EMACS)
        timeStamp =  datetime.datetime.fromtimestamp(modified_time).strftime("%b-%d-%y-%H:%M:%S")
        os.rename(EMACS, EMACS + ".bak_" + timeStamp)

backupEmacs()

with open(EMACS, 'w') as f:
    f.write(";; This .emacs is automatically generated by " + REPO_PATH + ".\n")
    f.write('(load "' + REPO_EMACS + '")')
